### ISSUE TITLE
DN to Reflectance

### ISSUE THREAD

**Issue by ddjustina** [pierreroudier/asdreader#1]
Hello, how do I convert the digital numbers to the actual reflectance values? Thank you very much, this is a very handy tool.

**Comment by pierreroudier** [comment]
The `get_spectra` function can return 3 types of data:
- DN
- Reflectance
- White reference

This is handled by the `type` option, and it should give you back reflectance values by default.

Try the following. Say `asd_fn` is the path to your ASD file:

```
# Get reflectance data
get_spectra(asd_fn, type = "reflectance")

# Get DN
get_spectra(asd_fn, type = "raw")

# Get WR
get_spectra(asd_fn, type = "white_reference")
```

For example on your machine, you can load the ASD file shipped with the `asdreader` package:

```
asd_fn <- asd_file()
print(asd_fn) # This will print the location of the ASD file on your machine
get_spectra(asd_fn)
```
