### ISSUE TITLE
type = 'reflectance' actually imports raw DN

### ISSUE THREAD

**Issue by elaliberte** [pierreroudier/asdreader#2]
Thanks for the package.

Link to one of my .asd files collected with ASD FieldSpec 4 and RS3 software:
https://drive.google.com/file/d/0B1scm-tn03aLbmNiY3BlQ0JZdGc/view?usp=sharing

When I run:

spec <- get_spectra(f, type = 'reflectance')

I actually obtain the raw DN, not the reflectance (I've checked, it is clearly the raw DN).

When I run:

spec <- get_spectra(f, type = 'raw')

I get:

Error in .process_spectra(spec, md, type) : 
  File only contains data of type reflectance.

The .asd file itself is fine. I can import it into SPECCHIO and see the raw DN and reflectance -- both are clearly available in the binary file. I suspect a problem with file version? Please advise. Thank you.

**Comment by elaliberte** [comment]
Please see my proposed change to fix the issue.

**Comment by wolfgang-boku** [comment]
I am having the exact same problem. Where can I find the fix?

Anyways, thanks for this package!

**Comment by elaliberte** [comment]
I have fixed this issue, as well as another one, and made a pull request. In the meantime, you can try installing the forked version of the package:
```{r}
library(devtools)
install_github("elaliberte/asdreader", ref = 'patch-1')
```

**Comment by pierreroudier** [comment]
@elaliberte Hi Etienne, apologies for the lag, I'm traveling at the moment so haven't had time to merge your pull. I should be able to do so in the next 24 hours.

Thank you so much for your help fixing the bug,

**Comment by wolfgang-boku** [comment]
Thanks for the quick responses!

For me, the forked version does not work. When using
`type = "reflectance"`
all values are "NaN", while white_reference and raw work fine.

**Comment by elaliberte** [comment]
I suspect the problem is when you normalise the raw DN using the `.normalise_spectrum` function.
Check this (replacing with your own path of course). What are your metadata values for these fields?
```
test <- get_metadata('pathToYourASDfile')
test$$splice1_wavelength
test$$splice2_wavelength
test$it
test$swir1_gain
test$swir2_gain
```

**Comment by wolfgang-boku** [comment]
All the mentioned variables are 0, except
`> test$it
[1] 34`
(and I suspect that the double-$-sign was a mistake)

Here's a document with the whole metadata output: https://docs.google.com/document/d/1c5OI8bW0f5ryQoRY2QhZzOfKaVCvb7wVk2MpKuY9SCo/edit?usp=sharing

**Comment by pierreroudier** [comment]
@elaliberte I just merged your patch. Thanks a lot! I added you to the list of contributors. Please let me know if you'd rather not.

@wolfgang-boku Any chance you'd be able to give us access to the file?

**Comment by wolfgang-boku** [comment]
Sure, there you go: https://drive.google.com/drive/folders/0B_vCW9F_77G3WWhIRDFISUhINTQ?usp=sharing

**Comment by pierreroudier** [comment]
@wolfgang-boku it seems https://github.com/pierreroudier/asdreader/pull/4 is fixing your problem (thanks for the PR @elaliberte). Version 0.1-3 is on its way to CRAN. Let me know if there still is a problem.
