### ISSUE TITLE
Error when using get_spectra for a folder

### ISSUE THREAD

**Issue by FedeMassetti** [pierreroudier/asdreader#5]
If I am indicating a folder instead of a single file for get_spectra I obtain an error.
Using the example 

> asd_fn <- asd_file()
> m1 <- get_spectra(asd_fn)

This works, but this is what happens if I try to put only the path to the folder instead of the single file (e.g. to open multiple *.asd files at once).

> asd_fn2 <- "D:/Documents/R/win-library/3.3/asdreader/extdata"
> m1 <- get_spectra(asd_fn2)
Error in file(fn, "rb") : cannot open the connection
In addition: Warning message:
In file(fn, "rb") :
  cannot open file 'D:/Documents/R/win-library/3.3/asdreader/extdata': Permission denied

**Comment by pierreroudier** [comment]
Could you please indicate the contents of your folder:

```
list.files( "D:/Documents/R/win-library/3.3/asdreader/extdata")
```

**Comment by FedeMassetti** [comment]
> list.files( "D:/Documents/R/win-library/3.3/asdreader/extdata")
[1] "soil.asd"          "spectrum10839.asd"

soil.asd was already present in the folder, spectrum10839.asd is one of my files.

When I run
> asd_fn2 <- "D:/Documents/R/win-library/3.3/asdreader/extdata/spectrum10839.asd"
> m1 <- get_spectra(asd_fn2)

and
> asd_fn2 <- "D:/Documents/R/win-library/3.3/asdreader/extdata/soil.asd"
> m1 <- get_spectra(asd_fn2)

No error occurs and files are read properly.

**Comment by pierreroudier** [comment]
You need to pass a vector of ASD files to `get_spectra`, not just a path:

```
asds <- list.files("D:/Documents/R/win-library/3.3/asdreader/extdata/", pattern = glob2rx("*.asd"), full.names = TRUE)
asds
m <- get_spectra(asds)
```

Let me know if this doesn't work and I'll reopen.
